format_version = 1
project_id = "project.editor_sample"
name = "Editor Sample Project"
project_version = "0.1.0"
asset_root = "assets"
startup_scene = "scenes/start.engine.scene.json"

[[packages]]
package_id = "editor_sample"
manifest = "assets/editor_sample.package.toml"
enabled = true

[settings]
window_width = 1440
window_height = 900
fullscreen = false
vsync = true
