workspace = { members = ["src/input", "src/renderer", "src/audio", "src/physics", "src/scripting", "src/events", "src/launch_shared", "apps/dungeon_dogfood", "apps/marching_terrain", "tools/engine_pack"] }

[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11"
log = "0.4"
renderer = { path = "src/renderer" }
engine_events = { path = "src/events" }
launch_shared = { path = "src/launch_shared" }
winit = "0.29"

[patch.crates-io]
#raw-window-handle = "0.6.2"
#ash = "0.38.0"

imgui-rs-vulkan-renderer = { git = "https://github.com/dhickel/imgui-rs-vulkan-renderer", branch = "dev" }
