workspace = { members = ["src/input", "src/renderer", "src/audio", "src/physics", "src/scripting", "apps/dungeon_dogfood", "apps/editor", "tools/engine_pack"] }

[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
#raw-window-handle = "0.6.2"
#ash = "0.38.0"

imgui-rs-vulkan-renderer = { git = "https://github.com/dhickel/imgui-rs-vulkan-renderer", branch = "dev" }
