//! Generated by richness_content_codegen. DO NOT EDIT.
//!
//! Schema version: enhanced-v3-richness-content/v1
//! Source hash: 51A9F189E39613481D4405802A808AE388455A4997415039D19AC50BF1952272

use super::content_types::{
    light_index, prop_index, CollisionBehavior, FalloffStyle, LayerOccupancy, PlacementClass,
    RarityTier, ShapeRule, VerticalRecipe,
};

#[rustfmt::skip]
pub const SCHEMA_VERSION: &str = "enhanced-v3-richness-content/v1";
#[rustfmt::skip]
pub const SOURCE_HASH: &str = "51A9F189E39613481D4405802A808AE388455A4997415039D19AC50BF1952272";

#[rustfmt::skip]
pub const ARCHETYPE_COUNT: usize = 30;
#[rustfmt::skip]
pub const PROP_COUNT: usize = 15;
#[rustfmt::skip]
pub const LIGHT_RECIPE_COUNT: usize = 12;
#[rustfmt::skip]
pub const THEME_COUNT: usize = 3;

#[rustfmt::skip]
pub const ARCHETYPE_IDS: &[&str] = &[
    "ambush_cross",
    "antechamber",
    "arena",
    "barracks",
    "bridge_crossing",
    "cistern",
    "crossroads",
    "entrance_hall",
    "flooded_crypt",
    "foundry",
    "gallery",
    "grand_arena",
    "grand_stair_hall",
    "grotto",
    "guard_hall",
    "hypostyle_hall",
    "kill_court",
    "ladder_hub",
    "observatory",
    "ossuary",
    "overlook_hall",
    "pit_room",
    "reliquary",
    "shrine",
    "spiral_tower",
    "throne_hall",
    "trapped_gallery",
    "treasury",
    "vault",
    "vestibule",
];

#[rustfmt::skip]
pub const ARCHETYPE_SPAN_MIN: &[[u32; 2]] = &[
    [192, 192],
    [128, 128],
    [320, 320],
    [192, 160],
    [160, 256],
    [192, 192],
    [224, 224],
    [192, 160],
    [192, 192],
    [224, 192],
    [160, 256],
    [384, 384],
    [192, 256],
    [192, 192],
    [192, 160],
    [256, 192],
    [256, 256],
    [160, 160],
    [224, 224],
    [160, 192],
    [224, 192],
    [192, 192],
    [192, 224],
    [224, 224],
    [192, 192],
    [288, 256],
    [192, 256],
    [192, 192],
    [160, 160],
    [128, 112],
];

#[rustfmt::skip]
pub const ARCHETYPE_SPAN_MAX: &[[u32; 2]] = &[
    [320, 320],
    [224, 224],
    [448, 448],
    [320, 256],
    [256, 448],
    [320, 320],
    [352, 352],
    [352, 256],
    [352, 320],
    [352, 320],
    [256, 448],
    [448, 448],
    [320, 512],
    [352, 352],
    [352, 224],
    [448, 320],
    [384, 384],
    [256, 512],
    [352, 512],
    [288, 352],
    [384, 320],
    [320, 320],
    [320, 384],
    [352, 352],
    [288, 512],
    [448, 384],
    [320, 448],
    [320, 320],
    [256, 256],
    [224, 192],
];

#[rustfmt::skip]
pub const ARCHETYPE_SHAPE: &[ShapeRule] = &[
    ShapeRule::Chamfer,
    ShapeRule::Rectangle,
    ShapeRule::Octagon,
    ShapeRule::Rectangle,
    ShapeRule::Rectangle,
    ShapeRule::Octagon,
    ShapeRule::Octagon,
    ShapeRule::Rectangle,
    ShapeRule::Rectangle,
    ShapeRule::Chamfer,
    ShapeRule::Rectangle,
    ShapeRule::Octagon,
    ShapeRule::Rectangle,
    ShapeRule::CompositePartition,
    ShapeRule::Rectangle,
    ShapeRule::Rectangle,
    ShapeRule::Octagon,
    ShapeRule::Rectangle,
    ShapeRule::Octagon,
    ShapeRule::Rectangle,
    ShapeRule::Rectangle,
    ShapeRule::Rectangle,
    ShapeRule::Chamfer,
    ShapeRule::Octagon,
    ShapeRule::Octagon,
    ShapeRule::Chamfer,
    ShapeRule::Rectangle,
    ShapeRule::Rectangle,
    ShapeRule::Rectangle,
    ShapeRule::Rectangle,
];

#[rustfmt::skip]
pub const ARCHETYPE_EXIT_DEGREE_MIN: &[u32] = &[
    3,
    2,
    2,
    2,
    2,
    1,
    3,
    1,
    1,
    1,
    2,
    2,
    2,
    1,
    2,
    2,
    1,
    2,
    1,
    1,
    2,
    1,
    1,
    1,
    2,
    1,
    2,
    1,
    1,
    2,
];

#[rustfmt::skip]
pub const ARCHETYPE_EXIT_DEGREE_MAX: &[u32] = &[
    5,
    3,
    4,
    3,
    2,
    3,
    6,
    3,
    3,
    3,
    4,
    4,
    4,
    3,
    4,
    4,
    2,
    4,
    2,
    3,
    3,
    2,
    2,
    3,
    2,
    3,
    3,
    2,
    2,
    3,
];

#[rustfmt::skip]
pub const ARCHETYPE_LAYER_OCCUPANCY: &[LayerOccupancy] = &[
    LayerOccupancy::Both,
    LayerOccupancy::Lower,
    LayerOccupancy::Both,
    LayerOccupancy::Lower,
    LayerOccupancy::Both,
    LayerOccupancy::Both,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
    LayerOccupancy::Both,
    LayerOccupancy::Both,
    LayerOccupancy::Lower,
    LayerOccupancy::Both,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
    LayerOccupancy::Both,
    LayerOccupancy::Both,
    LayerOccupancy::Lower,
    LayerOccupancy::Both,
    LayerOccupancy::Both,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
    LayerOccupancy::Both,
    LayerOccupancy::Both,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
    LayerOccupancy::Lower,
];

#[rustfmt::skip]
pub const ARCHETYPE_ROUTE_WITNESS: &[[u32; 2]] = &[
    [64, 80],
    [64, 80],
    [80, 96],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [80, 96],
    [64, 80],
    [64, 80],
    [64, 80],
    [80, 96],
    [80, 96],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
    [80, 96],
    [80, 96],
    [64, 80],
    [64, 80],
    [64, 80],
    [64, 80],
];

#[rustfmt::skip]
pub const ARCHETYPE_VERTICAL_RECIPE: &[VerticalRecipe] = &[
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::DropHole,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::Stairwell,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::LadderShaft,
    VerticalRecipe::OpenStairwell,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::DropHole,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::SpiralStair,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
    VerticalRecipe::None,
];

#[rustfmt::skip]
pub const ARCHETYPE_RARITY: &[RarityTier] = &[
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Uncommon,
    RarityTier::Uncommon,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Legendary,
    RarityTier::Common,
    RarityTier::Uncommon,
    RarityTier::Uncommon,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Rare,
    RarityTier::Common,
    RarityTier::Rare,
    RarityTier::Common,
    RarityTier::Common,
    RarityTier::Uncommon,
    RarityTier::Uncommon,
    RarityTier::Common,
];

#[rustfmt::skip]
pub const ARCHETYPE_NEGATIVE_SPACE_BUDGET: &[u32] = &[
    120,
    60,
    200,
    100,
    140,
    160,
    140,
    80,
    130,
    140,
    100,
    260,
    180,
    200,
    110,
    180,
    180,
    100,
    120,
    130,
    160,
    150,
    90,
    100,
    120,
    180,
    140,
    80,
    60,
    50,
];

#[rustfmt::skip]
pub const ARCHETYPE_SUPPORT_RULES: &[&str] = &[
    "grounded_floor_wall_pillar",
    "grounded_floor_wall",
    "grounded_floor_wall_pillar_buttress",
    "grounded_floor_wall",
    "grounded_floor_wall_bridge_paired_slab_omission",
    "grounded_floor_wall_pit_paired_slab_omission",
    "grounded_floor_wall_pillar",
    "grounded_floor_wall",
    "grounded_floor_wall",
    "grounded_floor_wall_buttress",
    "grounded_floor_wall",
    "grounded_floor_wall_pillar_buttress_upper_gallery",
    "grounded_floor_wall_stairwell_paired_slab_omission",
    "grounded_floor_wall_cave_shell",
    "grounded_floor_wall_buttress",
    "grounded_floor_wall_column_grid",
    "grounded_floor_wall_pillar_solid",
    "grounded_floor_wall_ladder_shaft_paired_slab_omission",
    "grounded_floor_wall_pillar_open_stairwell_slab_omission",
    "grounded_floor_wall",
    "grounded_floor_wall_overlook_balcony_paired_slab_omission",
    "grounded_floor_wall_drop_pit_paired_slab_omission",
    "grounded_floor_wall_pillar",
    "grounded_floor_wall_pillar",
    "grounded_floor_wall_center_column_spiral_stair_paired_slab_omission",
    "grounded_floor_wall_pillar_dais",
    "grounded_floor_wall",
    "grounded_floor_wall",
    "grounded_floor_wall",
    "grounded_floor_wall",
];

#[rustfmt::skip]
pub const ARCHETYPE_COST_SOURCE_FACES: &[u32] = &[
    480,
    220,
    820,
    360,
    460,
    500,
    540,
    340,
    440,
    540,
    440,
    960,
    620,
    580,
    420,
    700,
    680,
    340,
    580,
    400,
    500,
    440,
    520,
    500,
    560,
    720,
    480,
    380,
    280,
    200,
];

#[rustfmt::skip]
pub const ARCHETYPE_COST_BRUSHES: &[u32] = &[
    28,
    14,
    48,
    22,
    26,
    30,
    32,
    20,
    26,
    32,
    26,
    56,
    36,
    34,
    24,
    42,
    40,
    20,
    34,
    24,
    30,
    26,
    30,
    30,
    34,
    42,
    28,
    22,
    16,
    12,
];

#[rustfmt::skip]
pub const ARCHETYPE_COST_ENTITIES: &[u32] = &[
    6,
    3,
    8,
    6,
    5,
    6,
    5,
    4,
    7,
    8,
    5,
    10,
    8,
    6,
    6,
    8,
    9,
    5,
    8,
    7,
    6,
    6,
    7,
    5,
    7,
    9,
    7,
    6,
    5,
    3,
];

#[rustfmt::skip]
pub const ARCHETYPE_COST_LIGHTS: &[u32] = &[
    4,
    2,
    6,
    3,
    4,
    4,
    4,
    3,
    4,
    5,
    4,
    8,
    6,
    4,
    3,
    6,
    5,
    4,
    6,
    4,
    5,
    4,
    5,
    4,
    5,
    7,
    4,
    3,
    2,
    2,
];

#[rustfmt::skip]
pub const ZONE_NAMES: &[&str] = &[
    "conflict",
    "entrance",
    "landmark",
    "quiet",
    "transition",
];

#[rustfmt::skip]
pub const ARCHETYPE_ZONE_COMPAT: &[&[u32]] = &[
    &[4, 0],
    &[1, 4],
    &[0, 2],
    &[3, 4],
    &[4, 0],
    &[3, 4],
    &[4],
    &[1],
    &[3, 0],
    &[0, 2],
    &[4, 3],
    &[0, 2],
    &[4, 2],
    &[3, 4],
    &[4, 0],
    &[4, 2],
    &[0, 2],
    &[4, 3],
    &[3, 2],
    &[3, 0],
    &[4, 3, 0],
    &[0, 4],
    &[3, 2],
    &[3, 2],
    &[2, 4],
    &[2, 0],
    &[0, 4],
    &[3, 2],
    &[3, 4],
    &[1, 4],
];

#[rustfmt::skip]
pub const GRAMMAR_NAMES: &[&str] = &[
    "branch",
    "dead_end",
    "hub",
    "linear",
    "loop",
];

#[rustfmt::skip]
pub const ARCHETYPE_GRAMMAR_COMPAT: &[&[u32]] = &[
    &[0, 4],
    &[3, 0],
    &[2],
    &[0, 1],
    &[3],
    &[0, 1],
    &[2, 0],
    &[3],
    &[0, 1],
    &[0, 1],
    &[3],
    &[2],
    &[3],
    &[0, 1],
    &[3],
    &[3, 2],
    &[1, 0],
    &[2, 0],
    &[1],
    &[0, 1],
    &[3, 0],
    &[1, 0],
    &[1],
    &[1, 0],
    &[3],
    &[1, 0],
    &[3, 0],
    &[1],
    &[1],
    &[3],
];

#[rustfmt::skip]
pub const ARCHETYPE_PROP_REFS: &[&[u32]] = &[
    &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("brazier"), prop_index("sconce")],
    &[prop_index("bench"), prop_index("sconce")],
    &[prop_index("brazier"), prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("chain"), prop_index("sconce")],
    &[prop_index("bench"), prop_index("chest"), prop_index("sconce"), prop_index("hearth"), prop_index("shelf")],
    &[prop_index("chain"), prop_index("sconce"), prop_index("brazier"), prop_index("rubble_cluster")],
    &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("fountain_rim")],
    &[prop_index("brazier"), prop_index("sconce"), prop_index("rubble_cluster")],
    &[prop_index("sconce"), prop_index("brazier"), prop_index("bench")],
    &[prop_index("sarcophagus"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("chain"), prop_index("shelf")],
    &[prop_index("brazier"), prop_index("chain"), prop_index("rubble_cluster"), prop_index("cage"), prop_index("shelf"), prop_index("hearth")],
    &[prop_index("shelf"), prop_index("sconce"), prop_index("bench"), prop_index("altar")],
    &[prop_index("brazier"), prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("chain"), prop_index("cage"), prop_index("sconce"), prop_index("hearth")],
    &[prop_index("sconce"), prop_index("brazier"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("broken_pillar")],
    &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("sconce"), prop_index("fountain_rim"), prop_index("bench")],
    &[prop_index("brazier"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("chain")],
    &[prop_index("brazier"), prop_index("sconce"), prop_index("rubble_cluster"), prop_index("bench"), prop_index("shelf"), prop_index("altar")],
    &[prop_index("cage"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("broken_pillar"), prop_index("brazier")],
    &[prop_index("sconce"), prop_index("chain"), prop_index("rubble_cluster"), prop_index("bench")],
    &[prop_index("altar"), prop_index("sconce"), prop_index("shelf"), prop_index("brazier"), prop_index("bench"), prop_index("hearth")],
    &[prop_index("sarcophagus"), prop_index("rubble_cluster"), prop_index("shelf"), prop_index("sconce"), prop_index("chain")],
    &[prop_index("sconce"), prop_index("brazier"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("bench")],
    &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("cage")],
    &[prop_index("altar"), prop_index("sconce"), prop_index("chest"), prop_index("shelf"), prop_index("brazier")],
    &[prop_index("altar"), prop_index("sconce"), prop_index("brazier"), prop_index("bench")],
    &[prop_index("sconce"), prop_index("chain"), prop_index("brazier"), prop_index("rubble_cluster"), prop_index("broken_pillar")],
    &[prop_index("altar"), prop_index("brazier"), prop_index("sconce"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("chain")],
    &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("sconce"), prop_index("cage"), prop_index("broken_pillar"), prop_index("shelf")],
    &[prop_index("chest"), prop_index("urn_block"), prop_index("sconce"), prop_index("shelf"), prop_index("altar")],
    &[prop_index("chest"), prop_index("shelf"), prop_index("sconce"), prop_index("chain")],
    &[prop_index("sconce"), prop_index("bench")],
];

#[rustfmt::skip]
pub const ARCHETYPE_LIGHT_REFS: &[&[u32]] = &[
    &[light_index("dim_beam"), light_index("warm_hall"), light_index("cold_crypt")],
    &[light_index("entrance_torch"), light_index("warm_hall")],
    &[light_index("warm_hall"), light_index("grand_hall_grid"), light_index("dim_beam")],
    &[light_index("warm_hall"), light_index("dim_beam")],
    &[light_index("dim_beam"), light_index("warm_hall"), light_index("cold_crypt")],
    &[light_index("cistern_cool"), light_index("dim_beam"), light_index("cold_crypt")],
    &[light_index("warm_hall"), light_index("dim_beam")],
    &[light_index("entrance_torch"), light_index("warm_hall")],
    &[light_index("cold_crypt"), light_index("dim_beam"), light_index("shrine_focus")],
    &[light_index("foundry_fire"), light_index("warm_hall"), light_index("dim_beam")],
    &[light_index("warm_hall"), light_index("dim_beam"), light_index("shrine_focus")],
    &[light_index("grand_hall_grid"), light_index("warm_hall"), light_index("brutalist_flood"), light_index("dim_beam")],
    &[light_index("grand_hall_grid"), light_index("warm_hall"), light_index("entrance_torch")],
    &[light_index("cavern_gloom"), light_index("dim_beam"), light_index("cold_crypt")],
    &[light_index("warm_hall"), light_index("dim_beam")],
    &[light_index("grand_hall_grid"), light_index("warm_hall"), light_index("dim_beam")],
    &[light_index("cold_crypt"), light_index("dim_beam"), light_index("shrine_focus")],
    &[light_index("dim_beam"), light_index("warm_hall"), light_index("cold_crypt")],
    &[light_index("shrine_focus"), light_index("warm_hall"), light_index("dim_beam"), light_index("cold_crypt")],
    &[light_index("cold_crypt"), light_index("dim_beam")],
    &[light_index("warm_hall"), light_index("dim_beam"), light_index("grand_hall_grid")],
    &[light_index("cold_crypt"), light_index("dim_beam")],
    &[light_index("shrine_focus"), light_index("warm_hall"), light_index("dim_beam")],
    &[light_index("shrine_focus"), light_index("warm_hall")],
    &[light_index("warm_hall"), light_index("dim_beam"), light_index("grand_hall_grid")],
    &[light_index("grand_hall_grid"), light_index("warm_hall"), light_index("shrine_focus")],
    &[light_index("dim_beam"), light_index("warm_hall"), light_index("cold_crypt")],
    &[light_index("treasury_glint"), light_index("warm_hall")],
    &[light_index("treasury_glint"), light_index("dim_beam")],
    &[light_index("entrance_torch"), light_index("dim_beam")],
];

#[rustfmt::skip]
pub const MATERIAL_ROLE_NAMES: &[&str] = &[
    "accent",
    "ceiling",
    "floor",
    "pillar",
    "trim",
    "wall",
];

#[rustfmt::skip]
pub const ARCHETYPE_MATERIAL_ROLES: &[&[(u32, &str)]] = &[
    &[(5, "wall_stone"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_square"), (4, "trim_carved")],
    &[(5, "wall_ashlar"), (2, "floor_flagstone"), (1, "ceiling_flat"), (4, "trim_plain")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_round"), (4, "trim_carved"), (0, "accent_band")],
    &[(5, "wall_ashlar"), (2, "floor_flagstone"), (1, "ceiling_flat"), (4, "trim_plain")],
    &[(5, "wall_stone"), (2, "floor_slab"), (1, "ceiling_rough"), (4, "trim_carved"), (3, "pillar_square")],
    &[(5, "wall_stone"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_round"), (4, "trim_plain")],
    &[(5, "wall_stone"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_round"), (4, "trim_carved")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_flat"), (4, "trim_carved"), (0, "accent_band")],
    &[(5, "wall_stone"), (2, "floor_flagstone"), (1, "ceiling_vault"), (4, "trim_plain"), (0, "accent_dark")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_square"), (4, "trim_plain"), (0, "accent_dark")],
    &[(5, "wall_ashlar"), (2, "floor_flagstone"), (1, "ceiling_vault"), (4, "trim_carved"), (3, "pillar_square")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_round"), (4, "trim_carved"), (0, "accent_band")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_flat"), (3, "pillar_square"), (4, "trim_carved"), (0, "accent_band")],
    &[(5, "wall_stone"), (2, "floor_flagstone"), (1, "ceiling_rough"), (4, "trim_plain")],
    &[(5, "wall_stone"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_square"), (4, "trim_plain")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_flat"), (3, "pillar_round"), (4, "trim_carved"), (0, "accent_gilded")],
    &[(5, "wall_stone"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_round"), (4, "trim_carved"), (0, "accent_dark")],
    &[(5, "wall_stone"), (2, "floor_slab"), (1, "ceiling_rough"), (4, "trim_plain")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_vault"), (3, "pillar_round"), (4, "trim_carved"), (0, "accent_band")],
    &[(5, "wall_stone"), (2, "floor_flagstone"), (1, "ceiling_vault"), (4, "trim_plain"), (0, "accent_dark")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_square"), (4, "trim_carved")],
    &[(5, "wall_stone"), (2, "floor_flagstone"), (1, "ceiling_rough"), (4, "trim_plain"), (0, "accent_dark")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_flat"), (3, "pillar_square"), (4, "trim_carved"), (0, "accent_gilded")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_vault"), (3, "pillar_round"), (4, "trim_carved"), (0, "accent_gilded")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_rough"), (3, "pillar_round"), (4, "trim_carved"), (0, "accent_band")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_flat"), (3, "pillar_round"), (4, "trim_carved"), (0, "accent_gilded")],
    &[(5, "wall_stone"), (2, "floor_flagstone"), (1, "ceiling_rough"), (4, "trim_plain"), (3, "pillar_square")],
    &[(5, "wall_ashlar"), (2, "floor_slab"), (1, "ceiling_flat"), (4, "trim_carved"), (0, "accent_gilded")],
    &[(5, "wall_stone"), (2, "floor_flagstone"), (1, "ceiling_vault"), (4, "trim_plain")],
    &[(5, "wall_ashlar"), (2, "floor_flagstone"), (1, "ceiling_flat"), (4, "trim_plain")],
];

// Theme variants: [ancient=0, egyptian=1, brutalist=2]
#[rustfmt::skip]
pub const ARCHETYPE_THEME_MASSING: &[[&str; 3]] = &[
    ["chamfered ashlar crossing with corbeled corner piers and recessed alcoves above entry portals", "chamfered sandstone crossing with battered corner columns and painted lintel bands over portal openings", "chamfered board-formed concrete crossing with exposed steel tie-rod columns and raw formwork corner chamfers"],
    ["rectangular dressed-stone antechamber with shallow niche benches and wall-mounted sconce ledges", "rectangular smooth-plaster antechamber with low stone benches and lotus-bud sconce recesses", "rectangular board-formed concrete antechamber with cantilevered bench slabs and recessed steel sconce housings"],
    ["octagonal stone arena with corbeled gallery ledges, buttressed outer walls, and floor-level brazier pits", "octagonal columned hall with battered walls, papyrus-bud columns defining the arena ring, and raised torch platforms", "octagonal concrete arena with raw formwork piers, exposed tension cables ringing the upper gallery, and sunken floor pits"],
    ["rectangular stone barracks with recessed bunk alcoves, a central hearth, and wall-mounted sconce brackets", "rectangular mud-brick barracks with low sleeping platforms, storage niches, and central oil-lamp hearth", "rectangular concrete barracks with cantilevered sleeping slabs, steel lockers set into wall recesses, and a central heating block"],
    ["rectangular stone bridge spanning a void with arched under-struts, stone parapet walls with sconce niches, and paired slab omission below the bridge deck", "rectangular sandstone bridge with battered parapet walls, painted beam soffit, flanking obelisk-form brazier stands, and open void below with omitted floor slab", "rectangular concrete bridge with exposed steel cable railings, board-formed deck underside, bare conduit runs along parapet, and raw void below with omitted slab"],
    ["octagonal stone cistern with arched ceiling, perimeter column ring, central pool depression with fountain-rim surround, drop-hole entry through omitted ceiling slab, and wall-mounted chain descents", "octagonal plastered cistern chamber with battered columns, central basin with raised rim, drop entry through omitted ceiling slab, and wall-niche oil lamps", "octagonal concrete cistern with exposed aggregate walls, central sunken basin with steel grating rim, drop entry through omitted slab, and recessed cold-cathode light channels"],
    ["octagonal stone junction with central pillar, arched passage openings at cardinal and diagonal faces, recessed torch niches", "octagonal columned junction with central palm-form column, painted beam lintels, and elevated oil-lamp basins", "octagonal concrete junction with central structural pier, exposed conduit runs along chamfered wall faces, recessed fluorescent housings"],
    ["rectangular stone entry hall with flanking brazier plinths, a central processional aisle, and wall-mounted sconce niches", "rectangular sandstone entry hall with tapered portal pylons, flanking obelisk-form brazier stands, and painted ceiling beams", "rectangular concrete entry hall with recessed entrance portal, board-formed wall panels, and cantilevered steel bench slabs"],
    ["rectangular stone crypt with water-stained lower walls, partially submerged sarcophagus platforms, vaulted ceiling with seepage staining, and wall-niche bone shelves above the water line", "rectangular flooded tomb chamber with water-damaged painted relief walls, elevated sarcophagus platforms, submerged offering niches, and wall-mounted lamp recesses above the flood line", "rectangular concrete flooded vault with water-stained formwork walls, raised concrete sarcophagus bays, exposed rebar at the water line, and recessed cold-cathode light strips"],
    ["chamfered stone foundry with central raised forge hearth, wall-mounted chain hoists from ceiling bosses, tool shelves in chamfered alcoves, and heavy buttressed walls to contain heat", "chamfered mud-brick foundry with central clay furnace platform, wall-relief smithing scenes, storage shelf niches, and battered corner buttresses", "chamfered concrete foundry with central induction furnace block, overhead steel gantry with chain hoists, tool racks in chamfered wall recesses, and high-temperature exhaust cowls"],
    ["rectangular stone gallery with longitudinal barrel-vault ceiling, recessed display niches along walls, and terminal apse", "rectangular gallery hall with painted relief walls, shallow offering niches, and a rear shrine alcove with raised altar platform", "rectangular concrete gallery with exposed beam ceiling, recessed display bays, and a monolithic altar block at the far end"],
    ["octagonal grand arena with double-height corbeled gallery, massive buttressed outer walls, recessed spectator alcoves on upper level, and central floor-level ceremonial hearth pits", "octagonal grand columned hall with double-height battered walls, papyrus-bud columns supporting upper gallery, painted ceiling beams, raised torch platforms around the ring, and central offering hearth", "octagonal concrete grand arena with exposed steel tension-ring upper gallery, raw formwork piers, recessed fluorescent light coves, cantilevered observation platforms, and a central sunken furnace block"],
    ["rectangular grand stair hall with broad dressed-stone staircase ascending along one wall, corbeled landing platforms, arched portal openings at both levels, paired slab omission for the stairwell volume, and wall-mounted sconce niches at every half-landing", "rectangular grand stair hall with shallow-riser sandstone steps, painted dado bands along stair walls, intermediate landing platforms with brazier stands, paired slab omission for the stairwell, and lotus-bud column newels", "rectangular concrete grand stair hall with cantilevered stair treads projecting from board-formed walls, steel tube railings, exposed ceiling beam grid, paired slab omission for the stairwell, and recessed fluorescent coves at landings"],
    ["irregular carved-stone grotto with naturalistic ceiling vault, water-worn floor basin with fountain-rim surround, wall-niche sconce recesses carved into living rock, and rubble-fall perimeter", "irregular carved-sandstone grotto with smoothed wall faces transitioning to rough-hewn natural ceiling, a shallow central pool with raised rim, wall-niche lamp recesses, and fallen rubble at the margins", "irregular shotcrete grotto with exposed aggregate wall texture, a central sump basin with steel grating, recessed cold-cathode light coves following natural wall contours, and rubble-fall containment cages"],
    ["rectangular fortified hall with crenelated upper gallery, buttressed side walls, and recessed guard-post alcoves", "rectangular guard hall with battered outer walls, sentry niches at mid-height, and elevated torch platforms flanking the passage", "rectangular concrete guard hall with cantilevered upper walkway, steel mesh barriers, and recessed observation slots"],
    ["rectangular hypostyle hall with dense grid of stone columns, raised central nave ceiling with clerestory light slots, perimeter aisles, wall-niche shelf recesses, and a terminal altar dais", "rectangular hypostyle hall with papyrus-bud column grid, painted ceiling with astronomical motifs, raised central processional aisle, wall-relief offering scenes, shelf niches between columns, and a rear altar platform", "rectangular concrete hypostyle hall with grid of square structural columns, exposed beam-and-slab ceiling with recessed fluorescent channels, perimeter bench slabs, and a monolithic altar block at the far end"],
    ["octagonal death court with central sacrificial pillar, hanging chain restraints from ceiling bosses, and recessed wall cages", "octagonal judgment court with central scale-platform, wall-relief condemnation scenes, hanging chain restraints, and sealed canopic alcoves", "octagonal concrete execution chamber with central steel restraint column, overhead gantry chain drops, and wall-mounted containment cages"],
    ["rectangular stone ladder hub with wall-mounted iron-rung ladder ascending through a paired slab omission, landing ledges at both levels, recessed sconce niches along the shaft, and a central floor clear zone for dismount", "rectangular plastered ladder hub with wooden-rung shaft ascending through paired slab omission, low bench platforms at both landings, wall-niche lamp recesses flanking the ladder, and a clear dismount zone", "rectangular concrete ladder hub with steel-cage ladder ascending through paired slab omission, cantilevered landing slabs, recessed fluorescent coves along the shaft wall, and a marked floor dismount zone"],
    ["octagonal stone observatory with corbeled dome ceiling pierced by an open oculus, perimeter pillar ring, a central raised altar platform, wall-niche instrument shelves, paired slab omission for the open stairwell, and recessed observation alcoves", "octagonal painted observatory with celestial-motif ceiling, lotus-column ring, a central altar platform for astronomical instruments, wall-relief star charts, paired slab omission for the stairwell opening, and recessed oil-lamp niches", "octagonal concrete observatory with raw formwork dome and central skylight aperture, board-formed column ring, monolithic instrument platform, recessed steel shelving bays, paired slab omission for the stairwell, and cold-cathode light coves"],
    ["rectangular stone ossuary with wall-niche bone shelves, a central sarcophagus platform, and low barrel-vaulted ceiling", "rectangular painted tomb chamber with wall-relief funerary scenes, stacked sarcophagus bays, and canopic shelf niches", "rectangular concrete catacomb with stacked ossuary bays, exposed aggregate wall panels, and recessed cold-cathode light channels"],
    ["rectangular stone overlook hall with full-height wall along one side opening to a balcony overlooking a lower chamber, paired slab omission for the overlook void, corbeled balcony supports, stone parapet with sconce niches, and brazier plinths at balcony corners", "rectangular sandstone overlook hall with battered balcony wall opening to a lower chamber, paired slab omission for the overlook void, painted parapet with lotus-bud sconce brackets, and flanking brazier stands overlooking the space below", "rectangular concrete overlook hall with cantilevered balcony slab projecting over a lower void through paired slab omission, steel tube guardrail, board-formed back wall with recessed fluorescent coves, and bare conduit runs along the ceiling"],
    ["rectangular stone pit room with central drop-hole opening through paired slab omission, perimeter ledge at the upper level, wall-mounted chain descent anchors, sconce-lit landing zone at the lower floor, and rubble debris around the pit rim", "rectangular plastered pit room with central drop-hole through paired slab omission, upper perimeter ledge with warning-inscribed dado band, wall-mounted chain descent anchors, sconce-lit lower chamber, and sealed cage alcoves at the pit floor", "rectangular concrete pit room with central drop-hole through paired slab omission, upper-level platform with steel guardrail, chain ladder descent anchored to exposed rebar points, cold-cathode-lit lower chamber, and containment cages at the pit base"],
    ["chamfered stone reliquary chamber with central raised altar dais, corner pilaster bundles, and recessed reliquary niches with votive shelves", "chamfered painted reliquary sanctuary with central altar platform, lotus-bud corner columns, wall-relief offering scenes, and gilded chest alcoves", "chamfered concrete reliquary vault with monolithic altar block, recessed steel-frame display cases, and spotlight channels in chamfered ceiling coves"],
    ["octagonal stone shrine with central altar, radiating wall-niche shrines, corbeled ceiling dome, and perimeter pillar ring", "octagonal sanctuary with central raised altar, painted wall panels depicting deity processions, lotus-column ring, and gilded ceiling rosette", "octagonal concrete meditation chamber with central altar monolith, board-formed wall panels with recessed light coves, and perimeter bench slabs"],
    ["octagonal stone spiral tower with central 32×32 newel column, 12-step spiral stair ascending 192 units through paired slab omission, corbeled treads with 64-unit radial depth, wall-sconce niches at each quarter-turn, brazier-lit landing platforms at both levels, and chamfered octagonal envelope of minimum 224×224", "octagonal sandstone spiral tower with central 32×32 palm-form column, 12-step spiral stair ascending 192 units through paired slab omission, 64-unit radial treads, painted dado bands along the stair wall, wall-niche oil lamps at each quarter-turn, and brazier-lit landing platforms", "octagonal concrete spiral tower with central 32×32 structural column, 12-step cantilevered concrete spiral stair ascending 192 units through paired slab omission, 64-unit radial treads, steel tube central handrail, recessed fluorescent coves at each quarter-turn, and chamfered octagonal envelope of minimum 224×224"],
    ["chamfered stone throne hall with elevated central dais platform, flanking pillar bundles with recessed statue niches, chamfered corner alcoves with brazier plinths, an upper gallery with corbeled balcony, and a processional approach aisle", "chamfered painted throne hall with central raised dais platform, battered columns with lotus-bud capitals, wall-relief tribute scenes, chamfered corner niches with canopic clusters, an upper painted balcony, and a ceremonial approach path", "chamfered concrete throne hall with central monolithic altar-dais block, board-formed square columns defining the approach, chamfered corner alcoves with bare fluorescent coves, a cantilevered upper gallery with steel guardrail, and exposed conduit runs along the ceiling"],
    ["rectangular stone gallery with pressure-plate floor motifs, ceiling-height wall slots for blade traps, recessed sconce niches between trap stations, chain-rigged rubble drops from ceiling hatches, and cage alcoves at trap reset positions", "rectangular painted gallery with false-floor trap channels between column lines, wall-relief warning scenes, recessed oil-lamp niches at safe passing points, chain-rigged ceiling blocks, and sealed canopic alcoves at trap boundaries", "rectangular concrete gallery with exposed steel trip-wire conduits along floor channels, recessed fluorescent warning strips at trap edges, chain-rigged overhead block drops, containment cages at reset stations, and formwork-patterned walls with sensor alcoves"],
    ["rectangular stone treasury with vaulted ceiling, wall-niche coin shelves, central chest cluster on raised plinth, and gated alcove", "rectangular painted treasury chamber with gilded wall panels, sealed urn alcoves, low storage shelves, and a central offering table", "rectangular concrete vault chamber with steel deposit-box bays, recessed floor safe blocks, and overhead conduit spotlights"],
    ["rectangular stone vault with low barrel-vault ceiling, heavy iron-bound chests on stone plinths, and wall-mounted sconce brackets", "rectangular sealed storage chamber with smooth plaster walls, painted offering-shelf recesses, and low cedar chests with bronze fittings", "rectangular concrete strongroom with exposed form-tie pattern walls, recessed steel safe cabinets, and bare-bulb pendant lights"],
    ["rectangular stone vestibule with shallow entry alcove, flanking wall-sconce niches, and a low stone bench along one wall", "rectangular plastered vestibule with tapered entry, painted dado band, recessed oil-lamp niches, and a low mud-brick bench", "rectangular concrete vestibule with recessed entry portal, board-formed wall texture, cantilevered bench slab, and recessed ceiling light trough"],
];

#[rustfmt::skip]
pub const ARCHETYPE_THEME_SUPPORT: &[[&str; 3]] = &[
    ["grounded_floor_wall_pillar_ancient", "grounded_floor_wall_pillar_egyptian", "grounded_floor_wall_pillar_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_floor_wall_pillar_buttress_ancient", "grounded_floor_wall_pillar_buttress_egyptian", "grounded_floor_wall_pillar_buttress_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_bridge_ancient_paired_slab_omit", "grounded_bridge_egyptian_paired_slab_omit", "grounded_bridge_brutalist_paired_slab_omit"],
    ["grounded_pit_ancient_paired_slab_omit", "grounded_pit_egyptian_paired_slab_omit", "grounded_pit_brutalist_paired_slab_omit"],
    ["grounded_floor_wall_pillar_ancient", "grounded_floor_wall_pillar_egyptian", "grounded_floor_wall_pillar_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_floor_wall_buttress_ancient", "grounded_floor_wall_buttress_egyptian", "grounded_floor_wall_buttress_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_floor_wall_pillar_buttress_upper_ancient", "grounded_floor_wall_pillar_buttress_upper_egyptian", "grounded_floor_wall_pillar_buttress_upper_brutalist"],
    ["grounded_stairwell_ancient_paired_slab_omit", "grounded_stairwell_egyptian_paired_slab_omit", "grounded_stairwell_brutalist_paired_slab_omit"],
    ["grounded_cave_shell_ancient", "grounded_cave_shell_egyptian", "grounded_cave_shell_brutalist"],
    ["grounded_floor_wall_buttress_ancient", "grounded_floor_wall_buttress_egyptian", "grounded_floor_wall_buttress_brutalist"],
    ["grounded_column_grid_ancient", "grounded_column_grid_egyptian", "grounded_column_grid_brutalist"],
    ["grounded_floor_wall_pillar_solid_ancient", "grounded_floor_wall_pillar_solid_egyptian", "grounded_floor_wall_pillar_solid_brutalist"],
    ["grounded_ladder_shaft_ancient_paired_slab_omit", "grounded_ladder_shaft_egyptian_paired_slab_omit", "grounded_ladder_shaft_brutalist_paired_slab_omit"],
    ["grounded_open_stairwell_ancient_paired_slab_omit", "grounded_open_stairwell_egyptian_paired_slab_omit", "grounded_open_stairwell_brutalist_paired_slab_omit"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_overlook_ancient_paired_slab_omit", "grounded_overlook_egyptian_paired_slab_omit", "grounded_overlook_brutalist_paired_slab_omit"],
    ["grounded_drop_pit_ancient_paired_slab_omit", "grounded_drop_pit_egyptian_paired_slab_omit", "grounded_drop_pit_brutalist_paired_slab_omit"],
    ["grounded_floor_wall_pillar_ancient", "grounded_floor_wall_pillar_egyptian", "grounded_floor_wall_pillar_brutalist"],
    ["grounded_floor_wall_pillar_ancient", "grounded_floor_wall_pillar_egyptian", "grounded_floor_wall_pillar_brutalist"],
    ["grounded_spiral_stair_ancient_paired_slab_omit", "grounded_spiral_stair_egyptian_paired_slab_omit", "grounded_spiral_stair_brutalist_paired_slab_omit"],
    ["grounded_floor_wall_pillar_dais_ancient", "grounded_floor_wall_pillar_dais_egyptian", "grounded_floor_wall_pillar_dais_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
    ["grounded_floor_wall_ancient", "grounded_floor_wall_egyptian", "grounded_floor_wall_brutalist"],
];

#[rustfmt::skip]
pub const ARCHETYPE_THEME_PROP_REFS: &[[&[u32]; 3]] = &[
    [&[prop_index("rubble_cluster"), prop_index("chain"), prop_index("brazier"), prop_index("sconce"), prop_index("broken_pillar")], &[prop_index("rubble_cluster"), prop_index("brazier"), prop_index("sconce"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("cage"), prop_index("broken_pillar")]],
    [&[prop_index("bench"), prop_index("sconce"), prop_index("broken_pillar")], &[prop_index("bench"), prop_index("sconce"), prop_index("canopic_cluster")], &[prop_index("bench"), prop_index("sconce"), prop_index("cage")]],
    [&[prop_index("brazier"), prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("sconce")], &[prop_index("brazier"), prop_index("rubble_cluster"), prop_index("urn_block"), prop_index("sconce"), prop_index("canopic_cluster")], &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("cage"), prop_index("broken_pillar")]],
    [&[prop_index("bench"), prop_index("chest"), prop_index("sconce"), prop_index("hearth"), prop_index("shelf"), prop_index("broken_pillar")], &[prop_index("bench"), prop_index("chest"), prop_index("sconce"), prop_index("hearth"), prop_index("shelf"), prop_index("canopic_cluster")], &[prop_index("bench"), prop_index("chest"), prop_index("hearth"), prop_index("cage")]],
    [&[prop_index("chain"), prop_index("sconce"), prop_index("brazier"), prop_index("rubble_cluster"), prop_index("broken_pillar")], &[prop_index("chain"), prop_index("sconce"), prop_index("brazier"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("cage"), prop_index("broken_pillar")]],
    [&[prop_index("chain"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("fountain_rim"), prop_index("broken_pillar")], &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("fountain_rim"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("cage"), prop_index("broken_pillar")]],
    [&[prop_index("brazier"), prop_index("sconce"), prop_index("rubble_cluster"), prop_index("broken_pillar")], &[prop_index("brazier"), prop_index("sconce"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("sconce"), prop_index("brazier"), prop_index("bench"), prop_index("broken_pillar")], &[prop_index("sconce"), prop_index("brazier"), prop_index("bench"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("sconce"), prop_index("bench"), prop_index("chain"), prop_index("cage")]],
    [&[prop_index("sarcophagus"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("chain"), prop_index("shelf"), prop_index("broken_pillar")], &[prop_index("sarcophagus"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("shelf"), prop_index("canopic_cluster")], &[prop_index("sarcophagus"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("brazier"), prop_index("chain"), prop_index("rubble_cluster"), prop_index("cage"), prop_index("shelf"), prop_index("hearth"), prop_index("broken_pillar")], &[prop_index("brazier"), prop_index("chain"), prop_index("rubble_cluster"), prop_index("shelf"), prop_index("hearth"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("brazier"), prop_index("chain"), prop_index("rubble_cluster"), prop_index("cage"), prop_index("broken_pillar")]],
    [&[prop_index("shelf"), prop_index("sconce"), prop_index("bench"), prop_index("altar"), prop_index("broken_pillar")], &[prop_index("shelf"), prop_index("sconce"), prop_index("bench"), prop_index("altar"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("shelf"), prop_index("bench"), prop_index("altar"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("brazier"), prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("chain"), prop_index("sconce"), prop_index("hearth")], &[prop_index("brazier"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("hearth"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("chain"), prop_index("cage")]],
    [&[prop_index("sconce"), prop_index("brazier"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("broken_pillar")], &[prop_index("sconce"), prop_index("brazier"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("sconce"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("rubble_cluster"), prop_index("chain"), prop_index("sconce"), prop_index("fountain_rim"), prop_index("bench"), prop_index("broken_pillar")], &[prop_index("rubble_cluster"), prop_index("sconce"), prop_index("fountain_rim"), prop_index("bench"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("cage"), prop_index("bench"), prop_index("broken_pillar")]],
    [&[prop_index("brazier"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("chain"), prop_index("broken_pillar")], &[prop_index("brazier"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("bench"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("cage")]],
    [&[prop_index("brazier"), prop_index("sconce"), prop_index("rubble_cluster"), prop_index("bench"), prop_index("shelf"), prop_index("altar"), prop_index("broken_pillar")], &[prop_index("brazier"), prop_index("sconce"), prop_index("rubble_cluster"), prop_index("bench"), prop_index("shelf"), prop_index("altar"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("sconce"), prop_index("rubble_cluster"), prop_index("bench"), prop_index("shelf"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("cage"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("broken_pillar"), prop_index("brazier")], &[prop_index("cage"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("brazier"), prop_index("canopic_cluster")], &[prop_index("cage"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("broken_pillar")]],
    [&[prop_index("sconce"), prop_index("chain"), prop_index("rubble_cluster"), prop_index("bench"), prop_index("broken_pillar")], &[prop_index("sconce"), prop_index("rubble_cluster"), prop_index("bench"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("cage")]],
    [&[prop_index("altar"), prop_index("sconce"), prop_index("shelf"), prop_index("brazier"), prop_index("bench"), prop_index("hearth"), prop_index("broken_pillar")], &[prop_index("altar"), prop_index("sconce"), prop_index("shelf"), prop_index("brazier"), prop_index("bench"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("altar"), prop_index("sconce"), prop_index("shelf"), prop_index("bench"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("sarcophagus"), prop_index("rubble_cluster"), prop_index("shelf"), prop_index("sconce"), prop_index("chain"), prop_index("broken_pillar")], &[prop_index("sarcophagus"), prop_index("shelf"), prop_index("sconce"), prop_index("canopic_cluster"), prop_index("urn_block")], &[prop_index("sarcophagus"), prop_index("rubble_cluster"), prop_index("shelf"), prop_index("chain"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("sconce"), prop_index("brazier"), prop_index("rubble_cluster"), prop_index("chain"), prop_index("bench"), prop_index("broken_pillar")], &[prop_index("sconce"), prop_index("brazier"), prop_index("rubble_cluster"), prop_index("bench"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("bench"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("chain"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("cage"), prop_index("broken_pillar")], &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("sconce"), prop_index("cage"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("cage"), prop_index("broken_pillar")]],
    [&[prop_index("altar"), prop_index("sconce"), prop_index("chest"), prop_index("shelf"), prop_index("brazier"), prop_index("broken_pillar")], &[prop_index("altar"), prop_index("sconce"), prop_index("chest"), prop_index("shelf"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("altar"), prop_index("chest"), prop_index("shelf"), prop_index("chain"), prop_index("cage")]],
    [&[prop_index("altar"), prop_index("sconce"), prop_index("brazier"), prop_index("bench"), prop_index("broken_pillar")], &[prop_index("altar"), prop_index("sconce"), prop_index("brazier"), prop_index("bench"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("altar"), prop_index("bench"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("sconce"), prop_index("chain"), prop_index("brazier"), prop_index("rubble_cluster"), prop_index("broken_pillar")], &[prop_index("sconce"), prop_index("brazier"), prop_index("rubble_cluster"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("chain"), prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("cage")]],
    [&[prop_index("altar"), prop_index("brazier"), prop_index("sconce"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("chain")], &[prop_index("altar"), prop_index("brazier"), prop_index("sconce"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("altar"), prop_index("bench"), prop_index("rubble_cluster"), prop_index("broken_pillar"), prop_index("chain"), prop_index("cage")]],
    [&[prop_index("rubble_cluster"), prop_index("chain"), prop_index("sconce"), prop_index("cage"), prop_index("broken_pillar"), prop_index("shelf")], &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("sconce"), prop_index("cage"), prop_index("shelf"), prop_index("canopic_cluster")], &[prop_index("rubble_cluster"), prop_index("chain"), prop_index("cage"), prop_index("broken_pillar")]],
    [&[prop_index("chest"), prop_index("urn_block"), prop_index("sconce"), prop_index("shelf"), prop_index("altar"), prop_index("broken_pillar")], &[prop_index("chest"), prop_index("urn_block"), prop_index("sconce"), prop_index("shelf"), prop_index("canopic_cluster")], &[prop_index("chest"), prop_index("shelf"), prop_index("chain"), prop_index("cage")]],
    [&[prop_index("chest"), prop_index("shelf"), prop_index("sconce"), prop_index("chain"), prop_index("broken_pillar")], &[prop_index("chest"), prop_index("shelf"), prop_index("sconce"), prop_index("urn_block"), prop_index("canopic_cluster")], &[prop_index("chest"), prop_index("chain"), prop_index("cage")]],
    [&[prop_index("sconce"), prop_index("bench"), prop_index("broken_pillar")], &[prop_index("sconce"), prop_index("bench"), prop_index("canopic_cluster")], &[prop_index("sconce"), prop_index("bench"), prop_index("cage")]],
];

#[rustfmt::skip]
pub const ARCHETYPE_THEME_LIGHT_REFS: &[[&[u32]; 3]] = &[
    [&[light_index("dim_beam"), light_index("warm_hall")], &[light_index("dim_beam"), light_index("egyptian_amber")], &[light_index("dim_beam"), light_index("brutalist_flood")]],
    [&[light_index("entrance_torch"), light_index("warm_hall")], &[light_index("entrance_torch"), light_index("egyptian_amber")], &[light_index("entrance_torch"), light_index("brutalist_flood")]],
    [&[light_index("warm_hall"), light_index("grand_hall_grid"), light_index("dim_beam")], &[light_index("warm_hall"), light_index("egyptian_amber"), light_index("dim_beam")], &[light_index("brutalist_flood"), light_index("grand_hall_grid"), light_index("cold_crypt")]],
    [&[light_index("warm_hall"), light_index("dim_beam")], &[light_index("egyptian_amber"), light_index("dim_beam")], &[light_index("brutalist_flood"), light_index("cold_crypt")]],
    [&[light_index("dim_beam"), light_index("warm_hall")], &[light_index("dim_beam"), light_index("egyptian_amber")], &[light_index("dim_beam"), light_index("brutalist_flood")]],
    [&[light_index("cistern_cool"), light_index("dim_beam"), light_index("warm_hall")], &[light_index("cistern_cool"), light_index("egyptian_amber")], &[light_index("cistern_cool"), light_index("brutalist_flood")]],
    [&[light_index("warm_hall"), light_index("dim_beam")], &[light_index("egyptian_amber"), light_index("dim_beam")], &[light_index("brutalist_flood"), light_index("dim_beam")]],
    [&[light_index("entrance_torch"), light_index("warm_hall")], &[light_index("entrance_torch"), light_index("egyptian_amber")], &[light_index("entrance_torch"), light_index("brutalist_flood")]],
    [&[light_index("cold_crypt"), light_index("dim_beam"), light_index("shrine_focus"), light_index("warm_hall")], &[light_index("cold_crypt"), light_index("dim_beam"), light_index("shrine_focus"), light_index("egyptian_amber")], &[light_index("cold_crypt"), light_index("brutalist_flood"), light_index("dim_beam")]],
    [&[light_index("foundry_fire"), light_index("warm_hall"), light_index("dim_beam")], &[light_index("foundry_fire"), light_index("egyptian_amber"), light_index("dim_beam")], &[light_index("foundry_fire"), light_index("brutalist_flood"), light_index("dim_beam")]],
    [&[light_index("warm_hall"), light_index("dim_beam"), light_index("shrine_focus")], &[light_index("egyptian_amber"), light_index("dim_beam"), light_index("shrine_focus")], &[light_index("brutalist_flood"), light_index("cold_crypt"), light_index("shrine_focus")]],
    [&[light_index("grand_hall_grid"), light_index("warm_hall"), light_index("dim_beam")], &[light_index("grand_hall_grid"), light_index("egyptian_amber"), light_index("dim_beam")], &[light_index("grand_hall_grid"), light_index("brutalist_flood"), light_index("cold_crypt")]],
    [&[light_index("grand_hall_grid"), light_index("warm_hall"), light_index("entrance_torch")], &[light_index("grand_hall_grid"), light_index("egyptian_amber"), light_index("entrance_torch")], &[light_index("grand_hall_grid"), light_index("brutalist_flood"), light_index("entrance_torch")]],
    [&[light_index("cavern_gloom"), light_index("dim_beam"), light_index("cold_crypt"), light_index("warm_hall")], &[light_index("cavern_gloom"), light_index("dim_beam"), light_index("egyptian_amber")], &[light_index("cavern_gloom"), light_index("dim_beam"), light_index("brutalist_flood")]],
    [&[light_index("warm_hall"), light_index("dim_beam")], &[light_index("egyptian_amber"), light_index("dim_beam")], &[light_index("brutalist_flood"), light_index("cold_crypt")]],
    [&[light_index("grand_hall_grid"), light_index("warm_hall"), light_index("dim_beam")], &[light_index("grand_hall_grid"), light_index("egyptian_amber"), light_index("dim_beam")], &[light_index("grand_hall_grid"), light_index("brutalist_flood"), light_index("dim_beam")]],
    [&[light_index("cold_crypt"), light_index("dim_beam"), light_index("shrine_focus"), light_index("warm_hall")], &[light_index("cold_crypt"), light_index("dim_beam"), light_index("shrine_focus"), light_index("egyptian_amber")], &[light_index("brutalist_flood"), light_index("cold_crypt"), light_index("dim_beam")]],
    [&[light_index("dim_beam"), light_index("warm_hall")], &[light_index("dim_beam"), light_index("egyptian_amber")], &[light_index("dim_beam"), light_index("brutalist_flood"), light_index("cold_crypt")]],
    [&[light_index("shrine_focus"), light_index("warm_hall"), light_index("dim_beam"), light_index("cold_crypt")], &[light_index("shrine_focus"), light_index("egyptian_amber"), light_index("dim_beam"), light_index("cold_crypt")], &[light_index("shrine_focus"), light_index("brutalist_flood"), light_index("dim_beam")]],
    [&[light_index("cold_crypt"), light_index("dim_beam"), light_index("warm_hall")], &[light_index("cold_crypt"), light_index("dim_beam"), light_index("egyptian_amber")], &[light_index("cold_crypt"), light_index("brutalist_flood")]],
    [&[light_index("warm_hall"), light_index("dim_beam"), light_index("grand_hall_grid")], &[light_index("warm_hall"), light_index("egyptian_amber"), light_index("grand_hall_grid")], &[light_index("brutalist_flood"), light_index("dim_beam"), light_index("grand_hall_grid")]],
    [&[light_index("cold_crypt"), light_index("dim_beam"), light_index("warm_hall")], &[light_index("cold_crypt"), light_index("dim_beam"), light_index("egyptian_amber")], &[light_index("cold_crypt"), light_index("brutalist_flood"), light_index("dim_beam")]],
    [&[light_index("shrine_focus"), light_index("warm_hall"), light_index("dim_beam")], &[light_index("shrine_focus"), light_index("egyptian_amber"), light_index("dim_beam")], &[light_index("shrine_focus"), light_index("brutalist_flood"), light_index("dim_beam")]],
    [&[light_index("shrine_focus"), light_index("warm_hall")], &[light_index("shrine_focus"), light_index("egyptian_amber")], &[light_index("shrine_focus"), light_index("brutalist_flood")]],
    [&[light_index("warm_hall"), light_index("dim_beam"), light_index("grand_hall_grid")], &[light_index("warm_hall"), light_index("egyptian_amber"), light_index("grand_hall_grid")], &[light_index("brutalist_flood"), light_index("dim_beam"), light_index("grand_hall_grid")]],
    [&[light_index("grand_hall_grid"), light_index("warm_hall"), light_index("shrine_focus")], &[light_index("grand_hall_grid"), light_index("egyptian_amber"), light_index("shrine_focus")], &[light_index("grand_hall_grid"), light_index("brutalist_flood"), light_index("shrine_focus")]],
    [&[light_index("dim_beam"), light_index("warm_hall"), light_index("cold_crypt")], &[light_index("dim_beam"), light_index("egyptian_amber"), light_index("cold_crypt")], &[light_index("dim_beam"), light_index("brutalist_flood"), light_index("cold_crypt")]],
    [&[light_index("treasury_glint"), light_index("warm_hall")], &[light_index("treasury_glint"), light_index("egyptian_amber")], &[light_index("treasury_glint"), light_index("brutalist_flood")]],
    [&[light_index("treasury_glint"), light_index("dim_beam"), light_index("warm_hall")], &[light_index("treasury_glint"), light_index("dim_beam"), light_index("egyptian_amber")], &[light_index("treasury_glint"), light_index("brutalist_flood")]],
    [&[light_index("entrance_torch"), light_index("dim_beam"), light_index("warm_hall")], &[light_index("entrance_torch"), light_index("dim_beam"), light_index("egyptian_amber")], &[light_index("entrance_torch"), light_index("brutalist_flood")]],
];

#[rustfmt::skip]
pub const ARCHETYPE_THEME_MATERIALS: &[[&[&str]; 3]] = &[
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved", "pillar_square"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted", "pillar_lotus"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel", "pillar_square"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved", "pillar_square"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted", "pillar_lotus"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel", "pillar_square"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "pillar_square", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "pillar_lotus", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "pillar_square", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved", "pillar_square"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted", "pillar_lotus"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel", "pillar_square"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved", "accent_band"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted", "accent_gilded"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel", "accent_dark"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel"]],
    [&["wall_stone", "floor_flagstone", "ceiling_rough", "trim_carved"], &["wall_sandstone", "floor_flagstone", "ceiling_painted", "trim_painted"], &["wall_concrete", "floor_slab", "ceiling_beamgrid", "trim_steel"]],
];

#[rustfmt::skip]
pub const PROP_IDS: &[&str] = &[
    "altar",
    "bench",
    "brazier",
    "broken_pillar",
    "cage",
    "canopic_cluster",
    "chain",
    "chest",
    "fountain_rim",
    "hearth",
    "rubble_cluster",
    "sarcophagus",
    "sconce",
    "shelf",
    "urn_block",
];

#[rustfmt::skip]
pub const PROP_CONVEX_PIECES: &[u32] = &[
    3,
    1,
    3,
    2,
    5,
    3,
    1,
    2,
    4,
    4,
    3,
    2,
    1,
    1,
    2,
];

#[rustfmt::skip]
pub const PROP_DIMENSIONS: &[[u32; 3]] = &[
    [96, 48, 80],
    [64, 32, 32],
    [32, 32, 64],
    [48, 48, 32],
    [64, 64, 96],
    [48, 32, 48],
    [16, 16, 128],
    [48, 32, 32],
    [128, 128, 32],
    [96, 48, 64],
    [64, 64, 32],
    [96, 48, 64],
    [16, 16, 32],
    [64, 16, 32],
    [32, 32, 64],
];

#[rustfmt::skip]
pub const PROP_COLLISION: &[CollisionBehavior] = &[
    CollisionBehavior::Collidable,
    CollisionBehavior::Collidable,
    CollisionBehavior::DetailOnly,
    CollisionBehavior::Collidable,
    CollisionBehavior::Collidable,
    CollisionBehavior::DetailOnly,
    CollisionBehavior::DetailOnly,
    CollisionBehavior::Collidable,
    CollisionBehavior::Collidable,
    CollisionBehavior::Collidable,
    CollisionBehavior::Collidable,
    CollisionBehavior::Collidable,
    CollisionBehavior::DetailOnly,
    CollisionBehavior::Collidable,
    CollisionBehavior::Collidable,
];

#[rustfmt::skip]
pub const PROP_SWEPT_OCCUPANCY: &[[u32; 3]] = &[
    [112, 64, 96],
    [80, 48, 48],
    [48, 48, 80],
    [64, 64, 48],
    [80, 80, 112],
    [64, 48, 64],
    [32, 32, 144],
    [64, 48, 48],
    [144, 144, 48],
    [112, 64, 80],
    [80, 80, 48],
    [112, 64, 80],
    [32, 32, 48],
    [80, 32, 48],
    [48, 48, 80],
];

#[rustfmt::skip]
pub const PROP_SUPPORT_CONTACTS: &[u32] = &[
    4,
    2,
    1,
    3,
    4,
    1,
    1,
    4,
    4,
    3,
    6,
    4,
    1,
    2,
    1,
];

#[rustfmt::skip]
pub const PROP_LIGHT_COUPLING: &[&[u32]] = &[
    &[light_index("shrine_focus"), light_index("warm_hall")],
    &[light_index("warm_hall"), light_index("dim_beam")],
    &[light_index("warm_hall"), light_index("entrance_torch"), light_index("foundry_fire")],
    &[light_index("dim_beam"), light_index("cold_crypt")],
    &[light_index("cold_crypt"), light_index("dim_beam")],
    &[light_index("egyptian_amber"), light_index("shrine_focus")],
    &[light_index("dim_beam"), light_index("cold_crypt")],
    &[light_index("treasury_glint"), light_index("warm_hall")],
    &[light_index("cistern_cool"), light_index("dim_beam")],
    &[light_index("foundry_fire"), light_index("warm_hall")],
    &[light_index("dim_beam"), light_index("cavern_gloom")],
    &[light_index("cold_crypt"), light_index("shrine_focus")],
    &[light_index("entrance_torch"), light_index("warm_hall"), light_index("egyptian_amber")],
    &[light_index("dim_beam"), light_index("warm_hall")],
    &[light_index("egyptian_amber"), light_index("treasury_glint")],
];

#[rustfmt::skip]
pub const PROP_COST_SOURCE_FACES: &[u32] = &[
    36,
    12,
    36,
    24,
    60,
    36,
    12,
    24,
    48,
    48,
    36,
    24,
    12,
    12,
    24,
];

#[rustfmt::skip]
pub const PROP_COST_BRUSHES: &[u32] = &[
    3,
    1,
    3,
    2,
    5,
    3,
    1,
    2,
    4,
    4,
    3,
    2,
    1,
    1,
    2,
];

#[rustfmt::skip]
pub const PROP_COST_ENTITIES: &[u32] = &[
    1,
    1,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    1,
    1,
];

#[rustfmt::skip]
pub const PROP_COST_LIGHTS: &[u32] = &[
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    1,
    0,
    0,
];

#[rustfmt::skip]
pub const PROP_THEME_MODEL_OVERRIDE: &[[&str; 3]] = &[
    ["dressed-stone altar with carved rune channels and a polished granite table surface supported by corbeled bracket legs", "painted sandstone altar with lotus-bud corner finials, a raised offering table, and hieroglyph-inscribed base panels", "monolithic cast-concrete altar with board-formed texture, chamfered top edges, and exposed form-tie indentation pattern"],
    ["low stone bench with worn seating surface and roughly squared leg blocks at each end", "smooth mud-brick bench with plastered top surface and tapered end supports painted with dado-band motif", "cantilevered concrete bench slab projecting from wall with board-formed underside and exposed rebar anchors"],
    ["wrought-iron brazier on tripod stand with a hammered copper fire bowl, ornamental scrollwork legs, and ash-grate base", "cast-bronze brazier on a tapered stone pedestal with lotus-petal rim, offering-tray base, and painted flame-guard ring", "welded-steel brazier on a raw concrete plinth, industrial-grate fire basket, exposed bolt-flange assembly, and ash-catch tray"],
    ["fallen fluted stone column segment with a jagged fracture face, partially embedded base drum, and scattered capital fragments", "toppled papyrus-bud column section with painted band fragments, a clean-sheared top surface, and scattered hieroglyph-inscribed drum pieces", "collapsed square concrete column segment with exposed rebar ends, spalled surface aggregate, and a fractured base block with tie-rod remnants"],
    ["wrought-iron cage with floor-to-ceiling vertical bars, riveted corner straps, a heavy hinged door with draw-bar lock, and stone ballast base", "bronze-barred cage with lotus-finial corner posts, a painted wooden door with guardian-relief panels, and a stone threshold block", "welded steel-mesh cage with angle-iron frame, exposed bolt-plate corner assembly, a sliding bolt door, and raw concrete footing"],
    ["cluster of three alabaster canopic jars with animal-headed stoppers on a low stone offering plinth with carved dedication text", "grouped painted canopic jars with gilded human-headed stoppers on a raised limestone platform with hieroglyph-inscribed dedication panels", "set of three sealed steel canopic vessels with bolted lid assemblies on a concrete display pedestal with recessed ID plaques"],
    ["heavy wrought-iron chain with elongated oval links, a forged ceiling anchor ring, and a weighted hook terminus", "bronze-link chain with rectangular plate links, a ceiling-mounted stone anchor boss, and a ceremonial hook terminal", "galvanized steel chain with welded oval links, an eye-bolt ceiling anchor set in concrete, and a heavy-duty carabiner terminus"],
    ["iron-bound oak chest with riveted strap hinges, a heavy clasp lock, and raised plinth base with corner battens", "cedar-wood chest with bronze corner fittings, painted panel inlay depicting offering scenes, and a lotus-bud clasp", "steel plate chest with welded seam construction, industrial padlock hasp, and recessed lift handles on each end"],
    ["circular stone fountain rim with carved radial fluting, a raised basin edge of dressed ashlar blocks, and corner drain channels", "square sandstone basin rim with battered outer walls, a lotus-frieze band around the inner edge, and small corner offering platforms", "rectangular concrete basin rim with exposed aggregate finish, a steel angle-edge coping, and recessed corner drain grates"],
    ["stone hearth with a carved mantle shelf supported on corbel brackets, a raised firebox floor of fire-brick, and a soot-stained chimney breast", "mud-brick hearth with a painted plaster mantle depicting flame motifs, a recessed firebox with tapered sides, and a small offering ledge", "concrete hearth monolith with a board-formed mantle slab, a recessed steel firebox liner, and an exposed flue cowl above the chimney breast"],
    ["scattered fieldstone rubble with mixed-size angular fragments, a partially embedded broken lintel block, and gravel-fall debris", "fallen sandstone blocks with painted-relief fragments, a toppled corner finial piece, and scattered mud-brick debris", "shattered concrete fragments with exposed rebar stubs, a cracked slab section, and scattered aggregate debris with tie-rod remnants"],
    ["heavy stone sarcophagus with a peaked lid carved in low relief depicting a recumbent figure, corner acroteria, and a raised plinth base with dedication band", "painted wooden sarcophagus with gilded face-mask lid, polychrome body panels depicting journey scenes, and a low stone bier base", "cast-concrete burial vault with a flat slab lid, recessed steel lifting eyes at each corner, and a plain plinth base with form-tie marks"],
    ["wrought-iron wall sconce with a spiral bracket arm, a hammered copper drip pan, and a socket for torch or oil-lamp insertion", "carved stone wall sconce with a lotus-bud bracket, a shallow oil-reservoir basin, and painted flame-guard side wings", "steel bracket wall sconce with a welded angle-plate mount, a bare-bulb cage housing, and exposed conduit feed from above"],
    ["stone wall shelf formed by a projecting single-slab corbel with roughly dressed top surface and rounded front edge", "painted wooden shelf supported on carved stone corbel brackets with lotus-bud terminals and a smooth plastered top surface", "cantilevered concrete shelf slab projecting from a board-formed wall with a steel angle-edge coping and exposed anchor bolts"],
    ["tall ceramic funerary urn with a narrow pedestal foot, rope-pattern neck band, twin loop handles, and a domed stopper lid on a square stone plinth", "painted alabaster offering urn with a flared rim, lotus-petal body relief, twin lug handles, and a gilded stopper on a tapered pedestal base", "spun-steel cylindrical urn with a welded base flange, bolted lid with lift ring, and a raw concrete display pedestal with recessed ID plate"],
];

#[rustfmt::skip]
pub const PROP_THEME_DIMENSIONS: &[[[u32; 3]; 3]] = &[
    [[96, 48, 80], [112, 48, 80], [96, 64, 80]],
    [[64, 32, 32], [80, 32, 32], [64, 48, 32]],
    [[32, 32, 64], [48, 32, 64], [32, 48, 64]],
    [[48, 48, 32], [64, 48, 32], [48, 64, 32]],
    [[64, 64, 96], [80, 64, 96], [64, 80, 96]],
    [[48, 32, 48], [64, 32, 48], [48, 48, 48]],
    [[16, 16, 128], [32, 16, 128], [16, 32, 128]],
    [[48, 32, 32], [64, 32, 32], [48, 48, 32]],
    [[128, 128, 32], [144, 128, 32], [128, 144, 32]],
    [[96, 48, 64], [112, 48, 64], [96, 64, 64]],
    [[64, 64, 32], [80, 64, 32], [64, 80, 32]],
    [[96, 48, 64], [112, 48, 64], [96, 64, 64]],
    [[16, 16, 32], [32, 16, 32], [16, 32, 32]],
    [[64, 16, 32], [80, 16, 32], [64, 32, 32]],
    [[32, 32, 64], [48, 32, 64], [32, 48, 64]],
];

#[rustfmt::skip]
pub const PROP_THEME_COLLISION_OVERRIDE: &[[Option<CollisionBehavior>; 3]] = &[
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
    [None, None, None],
];

#[rustfmt::skip]
pub const LIGHT_RECIPE_IDS: &[&str] = &[
    "brutalist_flood",
    "cavern_gloom",
    "cistern_cool",
    "cold_crypt",
    "dim_beam",
    "egyptian_amber",
    "entrance_torch",
    "foundry_fire",
    "grand_hall_grid",
    "shrine_focus",
    "treasury_glint",
    "warm_hall",
];

#[rustfmt::skip]
pub const LIGHT_COLOR: &[[u8; 3]] = &[
    [180, 200, 220],
    [40, 60, 100],
    [60, 140, 160],
    [100, 120, 180],
    [120, 110, 90],
    [255, 180, 60],
    [255, 160, 60],
    [255, 80, 20],
    [220, 210, 180],
    [255, 220, 100],
    [255, 230, 120],
    [255, 180, 100],
];

#[rustfmt::skip]
pub const LIGHT_INTENSITY: &[u32] = &[
    300,
    80,
    120,
    150,
    100,
    250,
    300,
    350,
    280,
    200,
    180,
    220,
];

#[rustfmt::skip]
pub const LIGHT_PLACEMENT_CLASS: &[PlacementClass] = &[
    PlacementClass::Ceiling,
    PlacementClass::Ambient,
    PlacementClass::Ambient,
    PlacementClass::Wall,
    PlacementClass::Ceiling,
    PlacementClass::Wall,
    PlacementClass::Wall,
    PlacementClass::Floor,
    PlacementClass::Ceiling,
    PlacementClass::Pendant,
    PlacementClass::Pendant,
    PlacementClass::Ceiling,
];

#[rustfmt::skip]
pub const LIGHT_FALLOFF: &[FalloffStyle] = &[
    FalloffStyle::Linear,
    FalloffStyle::InverseSquare,
    FalloffStyle::InverseSquare,
    FalloffStyle::Linear,
    FalloffStyle::Linear,
    FalloffStyle::Linear,
    FalloffStyle::Linear,
    FalloffStyle::InverseSquare,
    FalloffStyle::Linear,
    FalloffStyle::Linear,
    FalloffStyle::Linear,
    FalloffStyle::Linear,
];

#[rustfmt::skip]
pub const LIGHT_READABILITY_FLOOR: &[u32] = &[
    20,
    4,
    8,
    10,
    6,
    16,
    20,
    24,
    18,
    14,
    12,
    15,
];

#[rustfmt::skip]
pub const LIGHT_COUNT: &[u32] = &[
    40,
    12,
    16,
    30,
    50,
    35,
    20,
    12,
    48,
    16,
    12,
    60,
];

#[rustfmt::skip]
pub const LIGHT_COST_SOURCE_FACES: &[u32] = &[
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
];

#[rustfmt::skip]
pub const LIGHT_COST_BRUSHES: &[u32] = &[
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
];

#[rustfmt::skip]
pub const LIGHT_COST_ENTITIES: &[u32] = &[
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
];

#[rustfmt::skip]
pub const LIGHT_COST_LIGHTS: &[u32] = &[
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
];

#[rustfmt::skip]
pub const LIGHT_ENTITY_KEYS: &[&str] = &[
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
    "light",
    "_color",
    "style",
];

#[rustfmt::skip]
pub const LIGHT_ENTITY_VALUES: &[&str] = &[
    "300",
    "180 200 220",
    "0",
    "80",
    "40 60 100",
    "0",
    "120",
    "60 140 160",
    "0",
    "150",
    "100 120 180",
    "0",
    "100",
    "120 110 90",
    "0",
    "250",
    "255 180 60",
    "0",
    "300",
    "255 160 60",
    "1",
    "350",
    "255 80 20",
    "1",
    "280",
    "220 210 180",
    "0",
    "200",
    "255 220 100",
    "0",
    "180",
    "255 230 120",
    "0",
    "220",
    "255 180 100",
    "0",
];

#[rustfmt::skip]
pub const LIGHT_ENTITY_KEY_SPANS: &[(usize, usize)] = &[
    (0, 3),
    (3, 6),
    (6, 9),
    (9, 12),
    (12, 15),
    (15, 18),
    (18, 21),
    (21, 24),
    (24, 27),
    (27, 30),
    (30, 33),
    (33, 36),
];

#[rustfmt::skip]
pub const THEME_IDS: &[&str] = &[
    "ancient",
    "brutalist",
    "egyptian",
];

#[rustfmt::skip]
pub const THEME_SEMANTIC_ROLE_NAMES: &[&str] = &[
    "accent",
    "ceiling",
    "floor",
    "pillar",
    "trim",
    "wall",
];

#[rustfmt::skip]
pub const THEME_SEMANTIC_ROLES: &[&[u32]] = &[
    &[5, 2, 1, 3, 4, 0],
    &[5, 2, 1, 3, 4, 0],
    &[5, 2, 1, 3, 4, 0],
];

#[rustfmt::skip]
pub const THEME_TRANSITIONS: &[&[&str]] = &[
    &["portal_surround", "corridor_trim"],
    &["portal_surround", "corridor_trim"],
    &["portal_surround", "corridor_trim"],
];

#[rustfmt::skip]
pub const THEME_GEOMETRY_VOCABULARY: &[&[&str]] = &[
    &["rectangle", "octagon", "chamfer", "composite_partition", "barrel_vault", "corbel", "buttress", "recessed_niche", "engaged_column", "ashlar_masonry", "crenelated_gallery"],
    &["rectangle", "octagon", "chamfer", "composite_partition", "cantilever", "board_form", "exposed_conduit", "steel_railing", "tie_rod", "formwork_panel", "cold_cathode_cove", "monolithic_slab"],
    &["rectangle", "octagon", "chamfer", "composite_partition", "battered_wall", "painted_beam", "lotus_column", "papyrus_bud_capital", "dado_band", "hieroglyph_frieze", "offering_niche", "pylon_portal"],
];

#[rustfmt::skip]
pub const THEME_MATERIAL_ROLE_NAMES: &[&str] = &[
    "accent",
    "ceiling",
    "floor",
    "pillar",
    "trim",
    "wall",
];

#[rustfmt::skip]
pub const THEME_MATERIAL_ROLES: &[&[(u32, &str)]] = &[
    &[(5, "wall_stone"), (2, "floor_flagstone"), (1, "ceiling_rough"), (3, "pillar_square"), (4, "trim_carved"), (0, "accent_band")],
    &[(5, "wall_concrete"), (2, "floor_slab"), (1, "ceiling_beamgrid"), (3, "pillar_square"), (4, "trim_steel"), (0, "accent_dark")],
    &[(5, "wall_sandstone"), (2, "floor_flagstone"), (1, "ceiling_painted"), (3, "pillar_lotus"), (4, "trim_painted"), (0, "accent_gilded")],
];

#[rustfmt::skip]
pub const THEME_PROP_COMPAT: &[&[u32]] = &[
    &[prop_index("altar"), prop_index("bench"), prop_index("brazier"), prop_index("broken_pillar"), prop_index("cage"), prop_index("canopic_cluster"), prop_index("chain"), prop_index("chest"), prop_index("fountain_rim"), prop_index("hearth"), prop_index("rubble_cluster"), prop_index("sarcophagus"), prop_index("sconce"), prop_index("shelf"), prop_index("urn_block")],
    &[prop_index("altar"), prop_index("bench"), prop_index("brazier"), prop_index("broken_pillar"), prop_index("cage"), prop_index("canopic_cluster"), prop_index("chain"), prop_index("chest"), prop_index("fountain_rim"), prop_index("hearth"), prop_index("rubble_cluster"), prop_index("sarcophagus"), prop_index("sconce"), prop_index("shelf"), prop_index("urn_block")],
    &[prop_index("altar"), prop_index("bench"), prop_index("brazier"), prop_index("broken_pillar"), prop_index("cage"), prop_index("canopic_cluster"), prop_index("chain"), prop_index("chest"), prop_index("fountain_rim"), prop_index("hearth"), prop_index("rubble_cluster"), prop_index("sarcophagus"), prop_index("sconce"), prop_index("shelf"), prop_index("urn_block")],
];

#[rustfmt::skip]
pub const THEME_LIGHT_COMPAT: &[&[u32]] = &[
    &[light_index("brutalist_flood"), light_index("cavern_gloom"), light_index("cistern_cool"), light_index("cold_crypt"), light_index("dim_beam"), light_index("egyptian_amber"), light_index("entrance_torch"), light_index("foundry_fire"), light_index("grand_hall_grid"), light_index("shrine_focus"), light_index("treasury_glint"), light_index("warm_hall")],
    &[light_index("brutalist_flood"), light_index("cavern_gloom"), light_index("cistern_cool"), light_index("cold_crypt"), light_index("dim_beam"), light_index("egyptian_amber"), light_index("entrance_torch"), light_index("foundry_fire"), light_index("grand_hall_grid"), light_index("shrine_focus"), light_index("treasury_glint"), light_index("warm_hall")],
    &[light_index("brutalist_flood"), light_index("cavern_gloom"), light_index("cistern_cool"), light_index("cold_crypt"), light_index("dim_beam"), light_index("egyptian_amber"), light_index("entrance_torch"), light_index("foundry_fire"), light_index("grand_hall_grid"), light_index("shrine_focus"), light_index("treasury_glint"), light_index("warm_hall")],
];

#[rustfmt::skip]
pub const THEME_BUDGET_SOURCE_FACES: &[u32] = &[
    8000,
    8000,
    8000,
];

#[rustfmt::skip]
pub const THEME_BUDGET_BRUSHES: &[u32] = &[
    480,
    480,
    480,
];

#[rustfmt::skip]
pub const THEME_BUDGET_ENTITIES: &[u32] = &[
    120,
    120,
    120,
];

#[rustfmt::skip]
pub const THEME_BUDGET_LIGHTS: &[u32] = &[
    80,
    80,
    80,
];

#[rustfmt::skip]
pub const SPIRAL_LAYER_OFFSET: u32 = 192;

#[rustfmt::skip]
pub const SPIRAL_ENVELOPE_MIN: [u32; 2] = [224, 224];

#[rustfmt::skip]
pub const SPIRAL_STEP_COUNT: usize = 12;

#[rustfmt::skip]
pub const SPIRAL_STEP_INDEX: &[u32] = &[
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
];

#[rustfmt::skip]
pub const SPIRAL_STEP_RISE: &[u32] = &[
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
];

#[rustfmt::skip]
pub const SPIRAL_STEP_ENVELOPE: &[[u32; 2]] = &[
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
    [224, 224],
];

#[rustfmt::skip]
pub const SPIRAL_STEP_CENTER_COLUMN: &[[u32; 2]] = &[
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
    [32, 32],
];

#[rustfmt::skip]
pub const SPIRAL_STEP_TREAD_DEPTH: &[u32] = &[
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
];

#[rustfmt::skip]
pub const SPIRAL_STEP_IS_CONVEX: &[bool] = &[
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
];
