[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"

winit = { version = "0.29.0", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
input = { path = "../input" }
glam = "=0.8.5"
bytemuck = { version = "1.16.0", features = ["derive"] }
anyhow = "1.0"
once_cell = "1.10.0"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]



#game-loop = { version = "*", features = ["winit"] }
# Web



