[package]
name = "input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "=0.8.5"
enum-map = "2.7.3"
winit = { version = "0.30.1", features = ["rwh_05"] }
